#cloud-config
package_update: true
runcmd:
  - - zypper
    - -n
    - in
    - iptables
  - - zypper
    - -n
    - in
    - open-iscsi
  - - systemctl
    - enable
    - --now
    - iscsi
  - - systemctl
    - start
    - iscsi