#cloud-config
write_files:
- path: /etc/rancher/rke2/config.yaml
  owner: root
  content: |
    token: ${cluster_token}
    server: https://${lb_hostname}:9345
    tls-san:
      - ${lb_hostname}
    cni: cilium
    profile: cis
    protect-kernel-defaults: true
    kube-apiserver-arg:
      - "audit-log-maxage=30"
      - "audit-log-maxbackup=10"
      - "audit-log-maxsize=100"
    pod-security-admission-config-file: /etc/rancher/rke2/rancher-psact.yaml
    disable-kube-proxy: true
- path: /etc/sysctl.d/90-rke2.conf
  owner: root
  content: |
    net.ipv4.conf.all.forwarding=1
    net.ipv6.conf.all.forwarding=1
- path: /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
  owner: root
  content: |
    ---
    apiVersion: helm.cattle.io/v1
    kind: HelmChartConfig
    metadata:
      name: rke2-cilium
      namespace: kube-system
    spec:
      valuesContent: |-
        kubeProxyReplacement: true
        k8sServiceHost: 127.0.0.1
        k8sServicePort: 6443
        eni:
          enabled: true
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
            ingress:
              enabled: true
              hosts:
                - cilium.neuhauss.com.br
- path: /etc/rancher/rke2/rancher-psact.yaml
  owner: root
  content: |
    apiVersion: apiserver.config.k8s.io/v1
    kind: AdmissionConfiguration
    plugins:
    - configuration:
        apiVersion: pod-security.admission.config.k8s.io/v1
        defaults:
          audit: restricted
          audit-version: latest
          enforce: restricted
          enforce-version: latest
          warn: restricted
          warn-version: latest
        exemptions:
          namespaces:
          - ingress-nginx
          - kube-system
          - cattle-system
          - cattle-epinio-system
          - cattle-fleet-system
          - cattle-fleet-local-system
          - longhorn-system
          - cattle-neuvector-system
          - cattle-monitoring-system
          - rancher-alerting-drivers
          - cis-operator-system
          - cattle-csp-adapter-system
          - cattle-externalip-system
          - cattle-gatekeeper-system
          - cattle-resources-system
          - istio-system
          - cattle-istio-system
          - cattle-logging-system
          - cattle-windows-gmsa-system
          - cattle-sriov-system
          - cattle-ui-plugin-system
          - tigera-operator
          - rke2-update-so 
          - rke2-update
          - system-upgrade
          - suse-observability
          - stackstate
          - system-upgrade-controller
          - cattle-fleet-clusters-system
          - fleet-default
          - cattle-provisioning-capi-system
        kind: PodSecurityConfiguration
    name: PodSecurity
    path: ""
package_update: true
packages:
  - qemu-guest-agent
  - iptables
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
  - - sysctl
    - -w
    - net.ipv6.conf.all.disable_ipv6=1
  - - zypper
    - -n
    - in
    - iptables
  - - zypper 
    - -n
    - in
    - open-iscsi
  - - systemctl
    - enable
    - --now
  - - systemctl 
    - start
    - iscsi
  - curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION=${kubernetes_version} sh -
  - sysctl -p /etc/sysctl.d/90-rke2.conf
  - cp -f /usr/local/share/rke2/rke2-cis-sysctl.conf /etc/sysctl.d/60-rke2-cis.conf
  - systemctl restart systemd-sysctl
  - useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U
  - systemctl enable rke2-server.service
  - systemctl start rke2-server.service

